batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407152240
train_epochs: 1000
train_workers: 20
vocab: ;Q.WJj7oI!p+MkrgXCbZ2e#lnU:-3DLfq0s'E?wzu5Fv1xTO"6R*h(4BamdNHK&ytY)VciSA,P89/G
width: 128
