batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407111323
train_epochs: 1000
train_workers: 20
vocab: O.'z(jqfTd;WScHlbX*8igoeYV)-Paup9BMkRULxK0Jm7,!Et:F+D&#n/sZ"6143wNCAh2IvQyrG?5
width: 128
