batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 10
model_path: Models/03_handwriting_recognition\202407161116
train_epochs: 1000
train_workers: 20
vocab: litah.eudLoPwxfVymArOkpsEbGcMnjg,
width: 128
