batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407152235
train_epochs: 1000
train_workers: 20
vocab: jaq(Z-C+X86'T9)usrc*2w7zD;1v:,hR0mOEGngBd&YypbfNtAKWU4PQ"eixLM/VSo!lFH#.?5IkJ3
width: 128
