batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407120038
train_epochs: 1000
train_workers: 20
vocab: ofaW'(F&Y?CgT:Rv3.86Ds#XV)OQm,nNK;kp"dqAtH4/EZLi7c*rSI5jPGy-UuB!0hzexw+1M2J9lb
width: 128
