batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407160944
train_epochs: 1000
train_workers: 20
vocab: j:d!9g7)yTSbwsuKzqAOE".2*lcV/aBR-&fQLYWvI1tZXFpHxDG;60k+58e#M,CN3iPohm(r4?nJU'
width: 128
