batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407161101
train_epochs: 1000
train_workers: 20
vocab: jBUh-nIk:K.JubC&lPey'53Rpr*,OQX4o?0WtqVs27MSz!xm6)YEi+a8fNv(HZcG#gDTF1Ad9;w"/L
width: 128
