batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407121350
train_epochs: 1000
train_workers: 20
vocab: DrM7ZVeaw!buf:HBz1pxEsRjY-l0*8.vWoJqt2(I?,P;5"'cXTm/KFGiLQ+Ud36kAy)Og&h4#NS9Cn
width: 128
