batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407152242
train_epochs: 1000
train_workers: 20
vocab: -U7wkNZ,F58"XfCM/lEmW3gb0edI;Bc6Kq*&?H!s:tjOriT9zPaxu2p'nAJySG4oV.QL)h1Y#vD(+R
width: 128
