batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407152237
train_epochs: 1000
train_workers: 20
vocab: 0ld7mu6IUBfW3,!nTYQR.HyJt9/rLEgxq+k;NP(A-pMOc)h&'DobS1#2VsCZ8vG5we*X:aizj4F?K"
width: 128
