batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407111340
train_epochs: 1000
train_workers: 20
vocab: :zL*tQ+dwy(JO,RI)lD;C-5h!bMPNm2K?B&cArenZW7gvVG6kHsq1'a"F#/p.ESu04foYU38X9iTxj
width: 128
