batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407152228
train_epochs: 1000
train_workers: 20
vocab: Bd,gK.4l"Rhj&WP')1Y*Cu7GX6Tp?(fbxEezkIyNQA;Jt+M9raqonS!-D#m0V8ZOU/Hw:LviFs523c
width: 128
