batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202407152231.keras
train_epochs: 1000
train_workers: 20
vocab: M#FH,)-fdGZRYtI*vpzN01shLbA.Wa/VJ3y8qm'w&TSkE(r6ij"QC2?lePc7B!:U+;nD9XuxOKg5o4
width: 128
